import { useState, useEffect } from "react";
import { X, Calendar, Clock, Pill, CheckSquare, Download, Settings, Bell } from "lucide-react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { toast } from "sonner@2.0.3";

interface ActivityTrackingProps {
  isOpen: boolean;
  onClose: () => void;
}

interface ActivityLog {
  id: string;
  type: 'medication' | 'task';
  title: string;
  timestamp: Date;
  status: 'completed' | 'missed' | 'snoozed';
}

export function ActivityTracking({ isOpen, onClose }: ActivityTrackingProps) {
  const [activityLog, setActivityLog] = useState<ActivityLog[]>([]);
  const [autoSendTime, setAutoSendTime] = useState("23:00");
  const [isAutoSendEnabled, setIsAutoSendEnabled] = useState(true);

  // Load activity log and settings
  useEffect(() => {
    const savedLog = localStorage.getItem('enablex_activity_log');
    if (savedLog) {
      setActivityLog(JSON.parse(savedLog).map((item: any) => ({
        ...item,
        timestamp: new Date(item.timestamp)
      })));
    }

    const savedTime = localStorage.getItem('enablex_auto_send_time');
    if (savedTime) {
      setAutoSendTime(savedTime);
    }

    const savedEnabled = localStorage.getItem('enablex_auto_send_enabled');
    if (savedEnabled !== null) {
      setIsAutoSendEnabled(savedEnabled === 'true');
    }
  }, [isOpen]);

  // Save settings
  useEffect(() => {
    localStorage.setItem('enablex_auto_send_time', autoSendTime);
    localStorage.setItem('enablex_auto_send_enabled', isAutoSendEnabled.toString());
  }, [autoSendTime, isAutoSendEnabled]);

  // Check for auto-send time
  useEffect(() => {
    if (!isAutoSendEnabled) return;

    const checkAutoSend = () => {
      const now = new Date();
      const currentTime = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`;
      
      if (currentTime === autoSendTime) {
        sendDailyReport(true);
      }
    };

    const interval = setInterval(checkAutoSend, 60000); // Check every minute
    return () => clearInterval(interval);
  }, [autoSendTime, isAutoSendEnabled]);

  const generatePDFReport = () => {
    const today = new Date().toLocaleDateString();
    const todayActivities = activityLog.filter(log => 
      new Date(log.timestamp).toLocaleDateString() === today
    );

    // Generate simple text report (in real app, use jsPDF or similar)
    let report = `ENABLEX DAILY ACTIVITY REPORT\n`;
    report += `Date: ${today}\n`;
    report += `Generated: ${new Date().toLocaleString()}\n`;
    report += `\n${"=".repeat(50)}\n\n`;
    
    const medications = todayActivities.filter(a => a.type === 'medication');
    const tasks = todayActivities.filter(a => a.type === 'task');

    report += `MEDICATION SUMMARY\n`;
    report += `Total: ${medications.length}\n`;
    report += `Completed: ${medications.filter(m => m.status === 'completed').length}\n`;
    report += `Missed: ${medications.filter(m => m.status === 'missed').length}\n\n`;

    medications.forEach(med => {
      const time = new Date(med.timestamp).toLocaleTimeString();
      report += `${time} - ${med.title} - ${med.status.toUpperCase()}\n`;
    });

    report += `\n${"=".repeat(50)}\n\n`;

    report += `TASKS SUMMARY\n`;
    report += `Total: ${tasks.length}\n`;
    report += `Completed: ${tasks.filter(t => t.status === 'completed').length}\n\n`;

    tasks.forEach(task => {
      const time = new Date(task.timestamp).toLocaleTimeString();
      report += `${time} - ${task.title} - ${task.status.toUpperCase()}\n`;
    });

    report += `\n${"=".repeat(50)}\n\n`;
    report += `Report generated by EnableX\n`;

    return report;
  };

  const sendDailyReport = (isAuto = false) => {
    const report = generatePDFReport();
    
    // Get caregivers
    const savedCaregivers = localStorage.getItem('enablex_caregivers');
    if (!savedCaregivers) {
      toast.error("No caregivers to send report to");
      return;
    }

    const caregivers = JSON.parse(savedCaregivers);
    const familyCaregivers = caregivers.filter((c: any) => c.type === 'family');
    const recipients = familyCaregivers.length > 0 ? familyCaregivers : caregivers;

    // Simulate sending report (in real app, use email/SMS API)
    recipients.forEach((caregiver: any) => {
      console.log(`Sending daily report to ${caregiver.name} (${caregiver.phone}):`);
      console.log(report);
    });

    toast.success(
      isAuto ? "Auto-report sent!" : "Report sent to caregivers!", 
      {
        description: `Sent to ${recipients.length} contact(s)`,
        duration: 4000,
      }
    );

    // Log the send event
    const newLog: ActivityLog = {
      id: Date.now().toString(),
      type: 'medication',
      title: 'Daily report sent to caregivers',
      timestamp: new Date(),
      status: 'completed'
    };
    const updatedLog = [newLog, ...activityLog];
    setActivityLog(updatedLog);
    localStorage.setItem('enablex_activity_log', JSON.stringify(updatedLog));
  };

  const downloadReport = () => {
    const report = generatePDFReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `EnableX_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Report downloaded!");
  };

  const getTodayActivities = () => {
    const today = new Date().toLocaleDateString();
    return activityLog.filter(log => 
      new Date(log.timestamp).toLocaleDateString() === today
    );
  };

  const getWeekActivities = () => {
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    return activityLog.filter(log => 
      new Date(log.timestamp) >= weekAgo
    );
  };

  if (!isOpen) return null;

  const todayActivities = getTodayActivities();
  const weekActivities = getWeekActivities();
  const todayMeds = todayActivities.filter(a => a.type === 'medication');
  const todayTasks = todayActivities.filter(a => a.type === 'task');

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Portal Content */}
      <div className="relative w-full max-w-md bg-white rounded-[3rem] shadow-2xl overflow-hidden flex flex-col" style={{ height: '844px' }}>
        
        {/* Header */}
        <header className="bg-gradient-to-r from-indigo-500 to-purple-600 px-6 pt-12 pb-8 text-white">
          <div className="flex items-center justify-between mb-4">
            <div className="flex-1">
              <h1 className="text-white">Activity</h1>
              <p className="text-white/90 mt-1">{todayActivities.length} events today</p>
            </div>
            <Button 
              size="icon" 
              variant="ghost" 
              onClick={onClose}
              className="rounded-full bg-white/20 hover:bg-white/30 text-white w-12 h-12"
            >
              <X className="w-7 h-7" strokeWidth={2.5} />
            </Button>
          </div>
        </header>

        {/* Main Content */}
        <main className="flex-1 overflow-hidden flex flex-col">
          <div className="flex-1 overflow-y-auto px-6 py-6">
            <div className="space-y-6 pb-4">
              {/* Summary Cards */}
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-blue-50 border-2 border-blue-200 rounded-2xl p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Pill className="w-5 h-5 text-blue-600" />
                    <p className="text-blue-900">Medications</p>
                  </div>
                  <p className="text-3xl text-blue-700">{todayMeds.length}</p>
                  <p className="text-blue-600 text-sm">
                    {todayMeds.filter(m => m.status === 'completed').length} taken
                  </p>
                </div>

                <div className="bg-emerald-50 border-2 border-emerald-200 rounded-2xl p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <CheckSquare className="w-5 h-5 text-emerald-600" />
                    <p className="text-emerald-900">Tasks</p>
                  </div>
                  <p className="text-3xl text-emerald-700">{todayTasks.length}</p>
                  <p className="text-emerald-600 text-sm">
                    {todayTasks.filter(t => t.status === 'completed').length} completed
                  </p>
                </div>
              </div>

              {/* Auto-Send Settings */}
              <div className="bg-purple-50 border-2 border-purple-200 rounded-2xl p-5">
                <div className="flex items-center gap-3 mb-4">
                  <Bell className="w-6 h-6 text-purple-600" />
                  <h2 className="text-purple-900">Auto-Send Report</h2>
                </div>
                
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <Label className="text-purple-800 text-lg">Enable Auto-Send</Label>
                    <button
                      onClick={() => setIsAutoSendEnabled(!isAutoSendEnabled)}
                      className={`w-14 h-8 rounded-full transition-colors ${
                        isAutoSendEnabled ? 'bg-purple-500' : 'bg-neutral-300'
                      }`}
                    >
                      <div className={`w-6 h-6 bg-white rounded-full shadow-md transition-transform ${
                        isAutoSendEnabled ? 'translate-x-7' : 'translate-x-1'
                      }`} />
                    </button>
                  </div>

                  <div>
                    <Label className="text-purple-800 mb-2 block text-lg">Daily Send Time</Label>
                    <Input
                      type="time"
                      value={autoSendTime}
                      onChange={(e) => setAutoSendTime(e.target.value)}
                      className="h-14 text-lg rounded-xl border-2 border-purple-300"
                      disabled={!isAutoSendEnabled}
                    />
                    <p className="text-purple-600 text-sm mt-2">
                      Reports sent automatically to family caregivers
                    </p>
                  </div>
                </div>
              </div>

              {/* Today's Activity Log */}
              <div>
                <h2 className="text-neutral-800 mb-4">Today's Activity</h2>
                
                {todayActivities.length === 0 ? (
                  <div className="bg-neutral-50 border-2 border-neutral-200 rounded-2xl p-8 text-center">
                    <Calendar className="w-12 h-12 mx-auto mb-3 text-neutral-400 opacity-50" />
                    <p className="text-neutral-600">No activities logged today</p>
                  </div>
                ) : (
                  <div className="space-y-3">
                    {todayActivities.map((activity) => (
                      <div
                        key={activity.id}
                        className={`rounded-2xl p-5 border-2 ${
                          activity.type === 'medication'
                            ? 'bg-blue-50 border-blue-200'
                            : 'bg-emerald-50 border-emerald-200'
                        }`}
                      >
                        <div className="flex items-start gap-4">
                          <div className={`rounded-xl p-3 ${
                            activity.type === 'medication' ? 'bg-blue-100' : 'bg-emerald-100'
                          }`}>
                            {activity.type === 'medication' ? (
                              <Pill className={`w-6 h-6 ${
                                activity.type === 'medication' ? 'text-blue-600' : 'text-emerald-600'
                              }`} />
                            ) : (
                              <CheckSquare className="w-6 h-6 text-emerald-600" />
                            )}
                          </div>
                          <div className="flex-1">
                            <p className="text-neutral-800 mb-1">{activity.title}</p>
                            <div className="flex items-center gap-2 text-neutral-600 text-sm">
                              <Clock className="w-4 h-4" />
                              <span>{activity.timestamp.toLocaleTimeString()}</span>
                            </div>
                            <span className={`inline-block mt-2 px-3 py-1 rounded-lg text-sm ${
                              activity.status === 'completed' ? 'bg-green-100 text-green-800' :
                              activity.status === 'missed' ? 'bg-red-100 text-red-800' :
                              'bg-orange-100 text-orange-800'
                            }`}>
                              {activity.status.charAt(0).toUpperCase() + activity.status.slice(1)}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </main>

        {/* Footer */}
        <div className="bg-white border-t-2 border-neutral-100 px-6 py-6">
          <div className="grid grid-cols-2 gap-3 mb-4">
            <Button
              onClick={() => sendDailyReport(false)}
              className="bg-gradient-to-r from-purple-500 to-purple-600 hover:from-purple-600 hover:to-purple-700 text-white rounded-2xl py-6 shadow-md"
            >
              <Bell className="w-5 h-5 mr-2" />
              Send Now
            </Button>
            <Button
              onClick={downloadReport}
              className="bg-gradient-to-r from-indigo-500 to-indigo-600 hover:from-indigo-600 hover:to-indigo-700 text-white rounded-2xl py-6 shadow-md"
            >
              <Download className="w-5 h-5 mr-2" />
              Download
            </Button>
          </div>
          <Button 
            onClick={onClose}
            className="w-full bg-neutral-200 hover:bg-neutral-300 text-neutral-800 rounded-2xl py-6 shadow-md"
          >
            Back
          </Button>
        </div>
      </div>
    </div>
  );
}
